INSERT INTO products (id, name, category, description, price, image_url) VALUES
(1, 'Smart Watch', 'electronics', 'Smart Watch with fitness and notification features.', 7469.17, 'img/product2.jpeg'),
(2, 'Bluetooth Speaker', 'electronics', 'Portable speaker with deep bass.', 2489.17, 'img/product3.jpeg'),
(3, 'Laptop Stand', 'electronics', 'Adjustable laptop stand for desk.', 1659.17, 'img/product4.jpeg'),
(4, 'USB-C Hub', 'electronics', 'Multi-port USB-C adapter.', 3319.17, 'img/product5.jpeg'),
(5, 'Portable Charger', 'electronics', '10000mAh fast-charging power bank.', 2079.17, 'img/product6.jpeg'),
(6, 'Wireless Mouse', 'electronics', 'Ergonomic wireless mouse.', 1244.17, 'img/product7.jpeg'),
(7, 'Gaming Keyboard', 'electronics', 'RGB mechanical keyboard.', 4979.17, 'img/product8.jpeg'),
(8, 'HDMI Cable', 'electronics', 'High-speed HDMI cable.', 829.17, 'img/product9.jpeg'),
(9, 'Webcam', 'electronics', 'HD webcam for video calls.', 4149.17, 'img/product10.jpeg'),
(10, 'Wireless Headphones', 'electronics', 'Bluetooth over-ear headphones.', 4149.17, 'img/product1.jpeg'),

(11, 'Men''s T-Shirt', 'fashion', 'Cotton t-shirt in assorted colors.', 1659.17, 'img/fashion1.jpeg'),
(12, 'Women''s Summer Dress', 'fashion', 'Light and airy summer dress.', 2489.17, 'img/fashion2.jpeg'),
(13, 'Men''s Jeans', 'fashion', 'Stretch denim jeans.', 3319.17, 'img/fashion3.jpeg'),
(14, 'Women''s Handbag', 'fashion', 'Stylish handbag for daily use.', 4149.17, 'img/fashion4.jpeg'),
(15, 'Men''s Sneakers', 'fashion', 'Comfortable sneakers for casual wear.', 4979.17, 'img/fashion5.jpeg'),
(16, 'Women''s Sandals', 'fashion', 'Trendy summer sandals.', 2079.17, 'img/fashion6.jpeg'),
(17, 'Unisex Sunglasses', 'fashion', 'UV-protective sunglasses.', 1244.17, 'img/fashion7.jpeg'),
(18, 'Men''s Jacket', 'fashion', 'Warm and stylish jacket.', 6635.17, 'img/fashion8.jpeg'),
(19, 'Women''s Scarf', 'fashion', 'Lightweight scarf with patterns.', 1078.17, 'img/fashion9.jpeg'),
(20, 'Fashion Watch', 'fashion', 'Analog watch with a leather strap.', 2903.17, 'img/fashion10.jpeg'),

(21, 'Air Conditioner', 'home_appliances', '1.5 Ton Split AC.', 33199.17, 'img/home1.jpeg'),
(22, 'Washing Machine', 'home_appliances', 'Fully automatic washing machine.', 41499.17, 'img/home2.jpeg'),
(23, 'Refrigerator', 'home_appliances', 'Double door inverter fridge.', 49799.17, 'img/home3.jpeg'),
(24, 'Microwave Oven', 'home_appliances', 'Convection microwave with grill.', 12448.17, 'img/home4.jpeg'),
(25, 'Vacuum Cleaner', 'home_appliances', 'Bagless vacuum cleaner.', 10748.17, 'img/home5.jpeg'),
(26, 'Electric Kettle', 'home_appliances', '1.7L stainless steel electric kettle.', 2489.17, 'img/home6.jpeg'),
(27, 'Blender', 'home_appliances', 'Multi-speed kitchen blender.', 4149.17, 'img/home7.jpeg'),
(28, 'Toaster', 'home_appliances', '2-slice bread toaster.', 2079.17, 'img/home8.jpeg'),
(29, 'Ceiling Fan', 'home_appliances', 'Energy-efficient ceiling fan.', 7469.17, 'img/home9.jpeg'),
(30, 'Coffee Maker', 'home_appliances', 'Drip coffee maker with timer.', 6635.17, 'img/home10.jpeg');
